### ISSUE TITLE
Populate DB with quiz questions (1 POINT)

### ISSUE THREAD

**Issue by roberthampton** [LachlanDow/Industry_Proj_Team5#4]

**Comment by rjhayward** [comment]
*50,000 questions with their answers and choices have been inserted into the database.

Do we want to include all of these questions or spend some time choosing a couple hundred good questions?

as the dataset is so huge, a large amount of questions are obscure and might make the game boring
Which categories do we want to include?

there are 22 categories which is quite a big number especially as it is supposed to be a simple web-app
