### ISSUE TITLE
Research into cookie

### ISSUE THREAD

**Issue by LachlanDow** [LachlanDow/Industry_Proj_Team5#58]
Notes written on teams, documentation linked: https://github.com/expressjs/cookie-session

**Comment by roberthampton** [comment]
Looks good, a few decent options there. I think using a Cookie Session from Express looks like the best option so this is something we can discuss further when it comes to implementation. Before we close the issue, could you please add a link to the documentation in the links page and maybe comment on this story as well just so it is easy to find later?

**Comment by khanjason** [comment]
Cool, this is the link to cookie-session documentation : https://github.com/expressjs/cookie-session
I'll put it in the word doc as well as other documentation for the other libraries

**Comment by roberthampton** [comment]
Good stuff, thank you. I've added a link to your word document in the links channel on Teams as well. Closing this issue now.
