### ISSUE TITLE
SPIKE - Investigate UX for quiz

### ISSUE THREAD

**Issue by roberthampton** [LachlanDow/Industry_Proj_Team5#9]
Link to word document of research

https://dmail-my.sharepoint.com/:w:/g/personal/lxdow_dundee_ac_uk/EXtM_24hZxtNmbRfp9zUgQsBEJ76PL87fGn6-83ofGOF3Q?e=nvUaGs

**Comment by khanjason** [comment]
Document of research is thorough and very informative. Happy to close this issue.
